import type { Metadata } from 'next';
import { absoluteUrl } from '../../lib/site';
import LegalPageShell from '../../components/LegalPageShell';

export const metadata: Metadata = {
  title: 'Privacy Policy | Saleh Store',
  description: 'Privacy Policy for Saleh Store, an eBay affiliate deals hub.',
  alternates: { canonical: absoluteUrl('/privacy') },
};

export default function PrivacyPage() {
  return (
    <LegalPageShell title="Privacy Policy" effectiveDate="September 20, 2026">
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">1. About This Policy</h2><p>Welcome to Saleh Store (saleh-store.com, “we,” “us,” or “our”). This Privacy Policy explains what information may be collected when you use our website, how it is used, and the choices available to you.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">2. Information We Collect</h2><ul className="list-disc pl-6 space-y-2"><li><strong>Information you provide:</strong> If you contact us through our contact form, we may receive your name, email address, subject, and message.</li><li><strong>Usage and device information:</strong> Our analytics and infrastructure providers may process information such as pages viewed, browser/device information, approximate location derived from network information, and technical request data.</li><li><strong>Local preferences:</strong> Features such as favorites and recently viewed products may use browser local storage.</li><li><strong>Affiliate interactions:</strong> When you follow an eBay affiliate link, eBay and its affiliate systems may use tracking technologies to attribute qualifying activity to Saleh Store.</li></ul></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">3. How We Use Information</h2><ul className="list-disc pl-6 space-y-2"><li>Operate, secure, and maintain the website.</li><li>Understand site usage and improve performance and user experience.</li><li>Measure affiliate referrals and qualifying purchases.</li><li>Respond to messages submitted through our contact form.</li><li>Meet legal, security, and fraud-prevention obligations.</li></ul></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">4. Third-Party Services</h2><p>Saleh Store uses third-party infrastructure and analytics services, including Vercel Analytics/Speed Insights and Google Analytics. Outbound eBay links may involve the eBay Partner Network. Each provider may process information under its own privacy and cookie policies.</p><p className="mt-3">Once you leave Saleh Store for eBay, eBay controls the processing of information on its services. Review <a className="text-blue-600 dark:text-blue-400 hover:underline" href="https://www.ebay.com/help/policies/member-behaviour-policies/user-privacy-notice?id=4260" target="_blank" rel="noopener noreferrer">eBay’s User Privacy Notice</a>.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">5. Affiliate Disclosure</h2><p>Saleh Store participates in the eBay Partner Network. If you click an affiliate link and complete a qualifying transaction, we may receive a commission from eBay. This does not add an affiliate fee to the price you pay.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">6. Cookies and Similar Technologies</h2><p>We may use essential cookies and, where enabled, analytics or affiliate-related technologies. See our <a className="text-blue-600 dark:text-blue-400 hover:underline" href="/cookies">Cookie Policy</a> for more information.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">7. Data Sharing</h2><p>We do not sell your personal information. Information may be processed by service providers that operate our hosting, analytics, forms, security, and affiliate infrastructure, where necessary to provide those services or comply with law.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">8. Privacy Rights</h2><p>Depending on your location and applicable law, you may have rights to access, correct, delete, restrict, object to, or obtain a copy of certain personal information, and rights concerning consent or certain forms of sharing. Requests can be submitted through our <a className="text-blue-600 dark:text-blue-400 hover:underline" href="/contact">Contact Us</a> page. We may need to verify a request before acting on it.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">9. Data Retention and Security</h2><p>We retain information only for as long as reasonably necessary for the purposes described in this policy, legal obligations, dispute resolution, and security. No internet transmission or storage system can be guaranteed to be completely secure.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">10. International Visitors</h2><p>Our service may be accessed internationally. Third-party providers may process information in countries other than your own, subject to their applicable safeguards and policies.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">11. Children</h2><p>Saleh Store is not directed to children under 13, and we do not knowingly request personal information from children under 13.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">12. Changes</h2><p>We may update this Privacy Policy from time to time. The effective date at the top of this page indicates when the current version took effect.</p></section>
      <section><h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">13. Privacy Contact</h2><p>For privacy requests or questions, please use the <a className="text-blue-600 dark:text-blue-400 hover:underline" href="/contact">Saleh Store contact form</a>. No unverified dedicated privacy email address is published here.</p></section>
    </LegalPageShell>
  );
}
